CC = gcc
CFLAGS = -std=gnu99 -D_XOPEN_SOURCE

esqueleto-karatsuba: esqueleto-karatsuba.c
	${CC} ${CFLAGS} esqueleto-karatsuba.c -o esqueleto-karatsuba -lm
	
numSplitter: numSplitter.c
	${CC} ${CFLAGS} numSplitter.c -o numSplitter -lm