CC = gcc
CFLAGS = -std=gnu99 -D_XOPEN_SOURCE

all: esqueleto-karatsuba karatsubaPoten2

esqueleto-karatsuba: esqueleto-karatsuba.c
	${CC} ${CFLAGS} esqueleto-karatsuba.c -o esqueleto-karatsuba -lm
	
karatsubaPoten2: karatsubaPoten2.c
	${CC} ${CFLAGS} karatsubaPoten2.c -o karatsubaPoten2 -lm